from enum import Enum, auto

class CalculatorStates(Enum):
    """Состояния калькулятора"""
    INSTRUCTION = auto()
    MODE_SELECTION = auto()
    CATEGORIES = auto()
    EFFICIENCY = auto()
    TAX = auto()
    PRODUCT_SELECTION = auto()
    PRODUCT_SELECTION_MULTI = auto()
    QUANTITY = auto()
    MARKET_PRICE = auto()
    DRAWING_PRICE = auto()
    MATERIALS_LIST = auto()
    PRICE_INPUT = auto()
    PRICE_INPUT_MISSING = auto()
    RESULT = auto()
    RESULT_DETAIL = auto()
    EXPLANATION = auto()

class AdminStates(Enum):
    """Состояния админки"""
    MAIN_MENU = auto()
    CATEGORY_LIST = auto()
    CATEGORY_ADD_NAME = auto()
    PRODUCT_LIST = auto()
    PRODUCT_ADD_NAME = auto()
    PRODUCT_ADD_CATEGORY = auto()
    PRODUCT_ADD_PRICE = auto()
    PRODUCT_ADD_MULTIPLICITY = auto()
    NODE_LIST = auto()
    NODE_ADD_NAME = auto()
    NODE_ADD_CATEGORY = auto()
    NODE_ADD_PRICE = auto()
    NODE_ADD_MULTIPLICITY = auto()
    MATERIAL_LIST = auto()
    MATERIAL_ADD_NAME = auto()
    MATERIAL_ADD_CATEGORY = auto()
    EDIT_FIELD = auto()
    EDIT_NAME = auto()
    EDIT_CATEGORY = auto()
    EDIT_PRICE = auto()
    EDIT_MULTIPLICITY = auto()
    PRODUCT_LINK_NODE_SELECT = auto()
    PRODUCT_LINK_NODE_QUANTITY = auto()
    PRODUCT_LINK_MATERIAL_SELECT = auto()
    PRODUCT_LINK_MATERIAL_QUANTITY = auto()
    ADMIN_LIST = auto()
    ADMIN_ADD_ID = auto()
    ADMIN_ADD_CONFIRM = auto()
    SEARCH = auto()
